services:
  - type: web
    name: bubble-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    rootDir: frontend
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: bubble-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    rootDir: backend
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: your_database_url_here
